In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\lucot\Downloads\3 etapa\atividade4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx", header=2)
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [3]:
df.columns.tolist()

['UF',
 'COD. UF',
 'COD. MUNIC',
 'NOME DO MUNICÍPIO',
 'População Município 2010\n(Sinopse)',
 'População 2010 (Alterações de Limites até 2022)1',
 'População Censo 2022']

In [4]:
df.rename(columns={
    'UF': 'UF',
    'COD. UF': 'COD_UF',
    'COD. MUNIC': 'COD_MUNIC',
    'NOME DO MUNICÍPIO': 'NOME_MUNICIPIO',
    'População Município 2010\n(Sinopse)': 'POP_2010_SINOSE',
    'População 2010 (Alterações de Limites até 2022)1': 'POP_2010',
    'População Censo 2022': 'POP_2022'
}, inplace=True)
df.head()

,UF,COD_UF,COD_MUNIC,NOME_MUNICIPIO,POP_2010_SINOSE,POP_2010,POP_2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [5]:
df = df[df["UF"].str.len() == 2]
pop_estado = df.groupby("UF")[["POP_2010", "POP_2022"]].sum().reset_index()
pop_estado.head()

   UF    POP_2010    POP_2022
0  AC    733559.0    830018.0
1  AL   3120887.0   3127683.0
2  AM   3483985.0   3941613.0
3  AP    669526.0    733759.0
4  BA  14017071.0  14141626.0

In [6]:
pop_estado["CRESCIMENTO"] = pop_estado["POP_2022"] - pop_estado["POP_2010"]
pop_estado = pop_estado.sort_values("CRESCIMENTO", ascending=False).reset_index(drop=True)
pop_estado

,UF,POP_2010,POP_2022,CRESCIMENTO
27,SP,41262199.0,44411238.0,3149039.0
25,SC,6248436.0,7610361.0,1361925.0
9,GO,6001789.0,7056495.0,1054706.0
19,PR,10444526.0,11444380.0,999854.0
11,MG,19597330.0,20539989.0,942659.0
13,MT,3035122.0,3658649.0,623527.0
15,PA,7581051.0,8120131.0,539080.0
2,AM,3483985.0,3941613.0,457628.0
5,CE,8451644.0,8794957.0,343313.0
7,ES,3514952.0,3833712.0,318760.0
12,MS,2449024.0,2757013.0,307989.0
17,PE,8796055.0,9058931.0,262876.0
6,DF,2572159.0,2817381.0,245222.0
16,PB,3766528.0,3974687.0,208159.0
10,MA,6574789.0,6776699.0,201910.0
24,RS,10693929.0,10882965.0,189036.0
23,RR,450479.0,636707.0,186228.0
18,PI,3119097.0,3271199.0,152102.0
26,SE,2067852.0,2210004.0,142152.0
21,RN,3168027.0,3302729.0,134702.0
28,TO,1383445.0,1511460.0,128015.0
4,BA,14017071.0,14141626.0,124555.0
0,AC,733559.0,830018.0,96459.0
20,RJ,15989929.0,16055174.0,65245.0
3,AP,669526.0,733759.0,64233.0
22,RO,1562409.0,1581196.0,18787.0
1,AL,3120887.0,3127683.0,6796.0
8,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,0.0,0.0,0.0
14,Nota: Para o cálculo das taxas de crescimento ...,0.0,0.0,0.0

In [7]:
pop_estado.to_csv(r"C:\Users\lucot\Downloads\3 etapa\atividade4\populacao_estado.csv", sep=";", index=False)

In [8]:
pop_municipio = df.groupby(["UF", "NOME_MUNICIPIO"])[["POP_2010", "POP_2022"]].sum().reset_index()
pop_municipio.head()

   UF NOME_MUNICIPIO  POP_2010  POP_2022
0  AC     Acrelândia   12538.0   14021.0
1  AC   Assis Brasil    6072.0    8100.0
2  AC      Brasiléia   21398.0   26000.0
3  AC         Bujari    8471.0   12917.0
4  AC       Capixaba    8798.0   10392.0

In [9]:
pop_municipio["CRESCIMENTO"] = pop_municipio["POP_2022"] - pop_municipio["POP_2010"]
pop_municipio = pop_municipio.sort_values("CRESCIMENTO", ascending=False).reset_index(drop=True)
pop_municipio

      UF  NOME_MUNICIPIO    POP_2010    POP_2022  CRESCIMENTO
161   AM          Manaus   1802014.0   2063689.0     261675.0
803   DF        Brasília   2572159.0   2817381.0     245222.0
5358  SP       São Paulo  11253503.0  11451999.0     198496.0
5334  SP        Sorocaba    586816.0    723682.0     136866.0
976   GO         Goiânia   1301912.0   1437366.0     135454.0
...   ..             ...         ...         ...          ...
4240  RS    Porto Alegre   1409351.0   1332845.0     -76506.0
2436  PA           Belém   1393399.0   1303403.0     -89996.0
3670  RJ     São Gonçalo    999728.0    896744.0    -102984.0
3660  RJ  Rio de Janeiro   6320446.0   6211223.0    -109223.0
535   BA        Salvador   2675656.0   2417678.0    -257978.0

[5570 rows x 5 columns]

In [10]:
pop_municipio.to_csv(r"C:\Users\lucot\Downloads\3 etapa\atividade4\populacao_municipio.csv", sep=";", index=False)